name: Deploy Monorepo to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Define environment variables needed for wrangler deploy later
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo Cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Run Cached Monorepo Build
        run: pnpm run build

      # --- Deployment 1: General App (mydomain.com) ---
      - name: Deploy General App to Cloudflare Pages
        run: npx wrangler pages deploy apps/general/dist --project-name=${{ secrets.PAGES_PROJECT_GENERAL }}

      # --- Deployment 2: Admin App (admin.mydomain.com) ---
      - name: Deploy Admin App to Cloudflare Pages
        run: npx wrangler pages deploy apps/admin/dist --project-name=${{ secrets.PAGES_PROJECT_ADMIN }}
